baseURL = "https://deedone.github.io/"
languageCode = "en-us"
title = "Tech Adventures"
theme = "noteworthy"
showReadMore = true
[markup.goldmark.renderer]
unsafe = true

googleAnalytics = "UA-163808068-1"

[params]
description = "Remember to create exponentially"

github = "https://github.com/Deedone"
telegram = "https://t.me/deedone"


[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 3
