baseURL = "https://techadv.xyz/"
languageCode = "en-us"
title = "Tech Adventures"
theme = "noteworthy"
showReadMore = true
[markup.goldmark.renderer]
unsafe = true


googleAnalytics = "UA-163808068-1"

[params]
description = "Remember to create exponentially"
description2 = "Just a small blog where I will document my exploration of interesting technologies, such as WASM, WebGL, Rust and more"

github = "https://github.com/Deedone"
telegram = "https://t.me/deedone"


[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 3
